### ISSUE TITLE
Add Humble Support

### ISSUE THREAD

**Issue by kjeremy** [blackcoffeerobotics/slim_bridge#1]
It looks like this supports `foxy`. Does it support `humble`?

**Comment by kvkpraneeth** [comment]
Hi, thank you for your interest! ROS1 `noetic` and ROS2 `foxy` versions are supported on Ubuntu 20.04. While ROS2 `humble` version is supported on Ubuntu 22.04. Hence, it would not make sense to port the ROS2 version from `foxy` to `humble`.

But if your use case is to bridge between `noetic` and `humble` you can try the following architecture:
![Untitled Diagram drawio](https://user-images.githubusercontent.com/55596533/213162251-c34ec9cf-37de-4f70-bb38-c25e4da07d7b.png)
